"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from plotly.data import *

"""Built-in datasets for demonstration, educational and test purposes.
"""
__all__ = ["carshare", "election", "election_geojson", "experiment", "gapminder", "iris", "medals_wide", "medals_long", "stocks", "tips", "wind"]
