"""
This type stub file was generated by pyright.
"""

from .canica import CanICA
from .dict_learning import DictLearning

"""The :mod:`nilearn.decomposition` module includes a subject level \
variant of the :term:`ICA` called Canonical :term:`ICA`."""
__all__ = ["CanICA", "DictLearning"]
