"""
This type stub file was generated by pyright.
"""

from nilearn.plotting.html_document import HTMLDocument

"""Generate HTML reports."""
ESTIMATOR_TEMPLATES = ...
def generate_report(estimator): # -> HTMLReport:
    """Generate a report for Nilearn objects.

    Reports are useful to visualize steps in a processing pipeline.
    Example use case: visualize the overlap of a mask and reference image
    in NiftiMasker.

    Parameters
    ----------
    estimator : Object instance of BaseEstimator.
        Object for which the report should be generated.

    Returns
    -------
    report : HTMLReport

    """
    ...

class HTMLReport(HTMLDocument):
    """A report written as HTML.

    Methods such as ``save_as_html``, or ``open_in_browser``
    are inherited from class ``nilearn.plotting.html_document.HTMLDocument``.

    """
    def __init__(self, head_tpl, body, head_values=...) -> None:
        """Construct the ``HTMLReport`` class.

        Parameters
        ----------
        head_tpl : Template
            This is meant for display as a full page, eg writing on disk.
            This is the Template object used to generate the HTML head
            section of the report. The template should be filled with:

                - title: The title of the HTML page.
                - body: The full body of the HTML page. Provided through
                  the ``body`` input.

        body : :obj:`str`
            This parameter is used for embedding in the provided
            ``head_tpl`` template. It contains the full body of the
            HTML page.

        head_values : :obj:`dict`, optional
            Additional substitutions in ``head_tpl``.
            Default={}.

            .. note::
                This can be used to provide additional values
                with custom templates.

        """
        ...
    
    def __str__(self) -> str:
        ...
    


