"""
This type stub file was generated by pyright.
"""

"""Utility functions for the reporting module."""
def figure_to_svg_bytes(fig): # -> bytes:
    """Save figure as svg and return it as bytes."""
    ...

def figure_to_svg_base64(fig): # -> str:
    """Save figure as svg and return it as 64 bytes."""
    ...

def figure_to_svg_quoted(fig): # -> str:
    """Save figure as svg and return it as quoted string."""
    ...

