"""
This type stub file was generated by pyright.
"""

"""Functions related to the documentation.

docdict contains the standard documentation entries
used across Nilearn.

Entries are listed in alphabetical order.

source: Eric Larson and MNE-python team.
https://github.com/mne-tools/mne-python/blob/main/mne/utils/docs.py
"""
docdict = ...
svc = ...
logistic = ...
rc = ...
dc = ...
memory_level = ...
n_jobs = ...
standardize = ...
verbose = ...
docdict_indented = ...
def fill_doc(f):
    """Fill a docstring with docdict entries.

    Parameters
    ----------
    f : callable
        The function to fill the docstring of. Will be modified in place.

    Returns
    -------
    f : callable
        The function, potentially with an updated `__doc__`.

    """
    ...

