"""
This type stub file was generated by pyright.
"""

AuthorizedException = ...
class DimensionError(TypeError):
    """Custom error type for dimension checking.

    This error is used in recursive calls in check_niimg to keep track of the
    dimensionality of the data. Its final goal it to generate a user friendly
    message.

    Parameters
    ----------
    file_dimension : integer
        Indicates the dimensonality of the bottom-level nifti file.

    required_dimension : integer
        The dimension the nifti file should have.

    """
    def __init__(self, file_dimension, required_dimension) -> None:
        ...
    
    def increment_stack_counter(self): # -> None:
        """Increments the counter of recursive calls.

        Called when the error is caught and re-raised to count the
        number of recursive calls, ie the number of dimensions added by
        imbrication in lists.

        """
        ...
    
    @property
    def message(self): # -> str:
        """Format error message."""
        ...
    
    def __str__(self) -> str:
        ...
    


