"""
This type stub file was generated by pyright.
"""

"""Extended math utilities."""
def fast_abs_percentile(data, percentile=...): # -> Any:
    """Implement a fast version of the percentile of the absolute value.

    Parameters
    ----------
    data : ndarray, possibly masked array
        The input data.

    percentile : number between 0 and 100
        The percentile that we are asking for.

    Returns
    -------
    value : number
        The score at percentile.

    Notes
    -----
    This is a faster, and less accurate version of
    scipy.stats.scoreatpercentile(np.abs(data), percentile)

    """
    ...

def is_spd(M, decimal=..., verbose=...): # -> Any | Literal[False]:
    """Assert that input matrix is symmetric positive definite.

    M must be symmetric down to specified decimal places.
    The check is performed by checking that all eigenvalues are positive.

    Parameters
    ----------
    M : numpy.ndarray
        Symmetric positive definite matrix.

    decimal : int, optional
        Decimal. Default=15.

    verbose : int, optional
        Verbosity level (0 means no message). Default=1.

    Returns
    -------
    answer : boolean
        True if matrix is symmetric positive definite, False otherwise.

    """
    ...

