"""
This type stub file was generated by pyright.
"""

"""N-dimensional image manipulation."""
def largest_connected_component(volume): # -> NDArray[Any] | Any:
    """Return the largest connected component of a 3D array.

    Parameters
    ----------
    volume : numpy.ndarray
        3D boolean array indicating a volume.

    Returns
    -------
    volume : numpy.ndarray
        3D boolean array with only one connected component.

    See Also
    --------
    nilearn.image.largest_connected_component_img : To simply operate the
        same manipulation directly on Nifti images.

    Notes
    -----
    **Handling big-endian in given numpy.ndarray**
    This function changes the existing byte-ordering information to new byte
    order, if the given volume has non-native data type. This operation
    is done inplace to avoid big-endian issues with scipy ndimage module.

    """
    ...

def get_border_data(data, border_size): # -> NDArray[Unknown]:
    """Return the data at the border of an array."""
    ...

