"""
This type stub file was generated by pyright.
"""

"""Neuroimaging file input and output."""
def load_niimg(niimg, dtype=...): # -> Nifti1Image | FileBasedImage:
    """Load a niimg, check if it is a nibabel SpatialImage and cast if needed.

    Parameters
    ----------
    niimg: Niimg-like object
        See :ref:`extracting_data`.
        Image to load.

    dtype: {dtype, "auto"}
        Data type toward which the data should be converted. If "auto", the
        data will be converted to int32 if dtype is discrete and float32 if it
        is continuous.

    Returns
    -------
    img: image
        A loaded image object.
    """
    ...

def copy_img(img): # -> Nifti1Image | FileBasedImage:
    """Copy an image to a nibabel.Nifti1Image.

    Parameters
    ----------
    img: image
        nibabel SpatialImage object to copy.

    Returns
    -------
    img_copy: image
        copy of input (data, affine and header)
    """
    ...

def img_data_dtype(niimg): # -> float_:
    """Determine type of data contained in image.

    Based on the information contained in ``niimg.dataobj``, determine the
    dtype of ``np.array(niimg.dataobj).dtype``.
    """
    ...

