"""
This type stub file was generated by pyright.
"""

"""Utilities to check for valid parameters."""
MNI152_BRAIN_VOLUME = ...
def check_threshold(threshold, data, percentile_func, name=...): # -> Real:
    """Check if the given threshold is in correct format \
    and within the limit.

    If necessary, this function also returns score of the data calculated based
    upon the given specific percentile function.
    Note: This is only for threshold as string.

    Parameters
    ----------
    threshold : float or str
        If threshold is a float value, it should be within the range of the
        maximum intensity value of the data.
        If threshold is a percentage expressed in a string it must finish with
        a percent sign like "99.7%".

    data : ndarray
        An array of the input masked data.

    percentile_func : function {scoreatpercentile, fastabspercentile}
        Percentile function for example scipy.stats.scoreatpercentile
        to calculate the score on the data.

    name : str, optional
        A string just used for representing
        the name of the threshold for a precise
        error message. Default='threshold'.

    Returns
    -------
    threshold : number
        Returns the score of the percentile on the data or
        returns threshold as it is
        if given threshold is not a string percentile.

    """
    ...

def check_feature_screening(screening_percentile, mask_img, is_classification, verbose=...): # -> SelectPercentile | None:
    """Check feature screening method.

    Turns floats between 1 and 100 into SelectPercentile objects.

    Parameters
    ----------
    screening_percentile : float in the interval [0, 100]
        Percentile value for ANOVA univariate feature selection. A value of
        100 means 'keep all features'. This percentile is expressed
        w.r.t the volume of a standard (MNI152) brain, and so is corrected
        at runtime by premultiplying it with the ratio of the volume of the
        mask of the data and volume of a standard brain.

    mask_img : nibabel image object
        Input image whose voxel dimensions are to be computed.

    is_classification : bool
        If is_classification is True, it indicates that a classification task
        is performed. Otherwise, a regression task is performed.

    verbose : int, optional
        Verbosity level. Default=0.

    Returns
    -------
    selector : SelectPercentile instance
       Used to perform the ANOVA univariate feature selection.

    """
    ...

