"""
This type stub file was generated by pyright.
"""

from pyparsing import ParseException
from matplotlib._fontconfig_pattern import *

family_unescape = ...
value_unescape = ...
family_escape = ...
value_escape = ...
class FontconfigPatternParser:
    ParseException = ParseException
    def parse(self, pattern): # -> dict[Unknown, Unknown]:
        ...
    


