"""
This type stub file was generated by pyright.
"""

from matplotlib._tight_layout import *
from matplotlib import _api

@_api.deprecated("3.6", alternative="figure.canvas.get_renderer()")
def get_renderer(fig): # -> Any | None:
    ...

