"""
This type stub file was generated by pyright.
"""

from .permuted_least_squares import permuted_ols

"""Define a Massively Univariate Linear Model estimated \
with OLS and permutation test."""
__all__ = ["permuted_ols"]
