"""
This type stub file was generated by pyright.
"""

import importlib
import warnings
from . import cm
from .find_cuts import find_cut_slices, find_parcellation_cut_coords, find_probabilistic_atlas_cut_coords, find_xyz_cut_coords
from .html_connectome import view_connectome, view_markers
from .html_stat_map import view_img
from .html_surface import view_img_on_surf, view_surf
from .img_plotting import plot_anat, plot_carpet, plot_connectome, plot_epi, plot_glass_brain, plot_img, plot_img_comparison, plot_markers, plot_prob_atlas, plot_roi, plot_stat_map, show
from .matrix_plotting import plot_contrast_matrix, plot_design_matrix, plot_event, plot_matrix
from .surf_plotting import plot_img_on_surf, plot_surf, plot_surf_contours, plot_surf_roi, plot_surf_stat_map

"""Plotting code for nilearn."""
OPTIONAL_MATPLOTLIB_MIN_VERSION = ...
__all__ = ["cm", "plot_img", "plot_anat", "plot_epi", "plot_roi", "plot_stat_map", "plot_glass_brain", "plot_markers", "plot_connectome", "plot_prob_atlas", "find_xyz_cut_coords", "find_cut_slices", "plot_img_comparison", "show", "plot_matrix", "plot_design_matrix", "plot_contrast_matrix", "plot_event", "view_surf", "view_img_on_surf", "view_img", "view_connectome", "view_markers", "find_parcellation_cut_coords", "find_probabilistic_atlas_cut_coords", "plot_surf", "plot_surf_stat_map", "plot_surf_roi", "plot_img_on_surf", "plot_carpet", "plot_surf_contours"]
