"""
This type stub file was generated by pyright.
"""

"""Brain schematics plotting for glass brain functionality."""
def plot_brain_schematics(ax, direction, **kwargs): # -> tuple[Unknown, Unknown, Unknown, Unknown]:
    """Create matplotlib patches from a json custom format and plot them \
    on a matplotlib Axes.

    Parameters
    ----------
    ax : A MPL axes instance
        The axes in which the plots will be drawn.

    direction : {'x', 'y', 'z', 'l', 'r'}
        The directions of the view.

    **kwargs :
        Passed to the matplotlib patches constructor.

    Returns
    -------
    object_bounds : (xmin, xmax, ymin, ymax) tuple
        Useful for the caller to be able to set axes limits.

    """
    ...

