"""
This type stub file was generated by pyright.
"""

from nilearn.plotting.html_document import HTMLDocument
from .._utils import fill_doc

"""Visualizing 3D stat maps in a Brainsprite viewer."""
class StatMapView(HTMLDocument):
    ...


@fill_doc
def view_img(stat_map_img, bg_img=..., cut_coords=..., colorbar=..., title=..., threshold=..., annotate=..., draw_cross=..., black_bg=..., cmap=..., symmetric_cmap=..., dim=..., vmax=..., vmin=..., resampling_interpolation=..., opacity=..., **kwargs): # -> StatMapView:
    """Interactive html viewer of a statistical map, with optional background.

    Parameters
    ----------
    stat_map_img : Niimg-like object
        See :ref:`extracting_data`.
        The statistical map image. Can be either a 3D volume or a 4D volume
        with exactly one time point.
    %(bg_img)s
        If nothing is specified, the MNI152 template will be used.
        To turn off background image, just pass "bg_img=False".
        Default='MNI152'.

    cut_coords : None, or a tuple of floats
        The MNI coordinates of the point where the cut is performed
        as a 3-tuple: (x, y, z). If None is given, the cuts are calculated
        automatically.

    colorbar : boolean, optional
        If True, display a colorbar on top of the plots. Default=True.
    %(title)s
    threshold : string, number or None, optional
        If None is given, the image is not thresholded.
        If a string of the form "90%%" is given, use the 90-th percentile of
        the absolute value in the image.
        If a number is given, it is used to threshold the image:
        values below the threshold (in absolute value) are plotted
        as transparent. If auto is given, the threshold is determined
        automatically. Default=1e-6.

    annotate : boolean, optional
        If annotate is True, current cuts are added to the viewer.
        Default=True.
    %(draw_cross)s
    black_bg : boolean or 'auto', optional
        If True, the background of the image is set to be black.
        Otherwise, a white background is used.
        If set to auto, an educated guess is made to find if the background
        is white or black.
        Default='auto'.
    %(cmap)s
        Default=`plt.cm.cold_hot`.
    symmetric_cmap : bool, optional
        True: make colormap symmetric (ranging from -vmax to vmax).
        False: the colormap will go from the minimum of the volume to vmax.
        Set it to False if you are plotting a positive volume, e.g. an atlas
        or an anatomical image. Default=True.
    %(dim)s
        Default='auto'.
    vmax : float, or None, optional
        max value for mapping colors.
        If vmax is None and symmetric_cmap is True, vmax is the max
        absolute value of the volume.
        If vmax is None and symmetric_cmap is False, vmax is the max
        value of the volume.

    vmin : float, or None, optional
        min value for mapping colors.
        If `symmetric_cmap` is `True`, `vmin` is always equal to `-vmax` and
        cannot be chosen.
        If `symmetric_cmap` is `False`, `vmin` defaults to the min of the
        image, or 0 when a threshold is used.
    %(resampling_interpolation)s
        Default='continuous'.
    opacity : float in [0,1], optional
        The level of opacity of the overlay (0: transparent, 1: opaque).
        Default=1.

    Returns
    -------
    html_view : the html viewer object.
        It can be saved as an html page `html_view.save_as_html('test.html')`,
        or opened in a browser `html_view.open_in_browser()`.
        If the output is not requested and the current environment is a Jupyter
        notebook, the viewer will be inserted in the notebook.

    See Also
    --------
    nilearn.plotting.plot_stat_map:
        static plot of brain volume, on a single or multiple planes.
    nilearn.plotting.view_connectome:
        interactive 3d view of a connectome.
    nilearn.plotting.view_markers:
        interactive plot of colored markers.
    nilearn.plotting.view_surf, nilearn.plotting.view_img_on_surf:
        interactive view of statistical maps or surface atlases on the cortical
        surface.

    """
    ...

