"""
This type stub file was generated by pyright.
"""

from .surface import Mesh, Surface, check_mesh_and_data, check_surface, load_surf_data, load_surf_mesh, load_surface, vol_to_surf

"""Functions for surface manipulation."""
__all__ = ["vol_to_surf", "load_surf_data", "load_surf_mesh", "load_surface", "check_surface", "check_mesh_and_data", "Mesh", "Surface"]
