---
name: Assign reviewer
on:
  pull_request_target:
    types: [opened, ready_for_review]
jobs:
  assign:
    runs-on: ubuntu-latest
    if: github.event.pull_request.assignee == null
    steps:
      - name: Assign reviewer
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
