---
name: Assign reviewer
on:
  pull_request_target:
    types: [opened, ready_for_review]
jobs:
  assign-reviewer:
    uses: khanlab/actions/.github/workflows/workflow-pr_task-assignReviewer.yml@v0.2.1
