---
name: Bump version
on:
  pull_request_target:
    types: [closed]
jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    uses: afids/actions/.github/workflows/bump_version.yml@main
    secrets:
      BP_PAT: ${{ secrets.BP_PAT_TOKEN }}