---
name: Release package
on:
  workflow_dispatch:
    inputs:
      comments:
        description: Comments
        required: false
jobs:
  release-package:
    uses: khanlab/actions/.github/workflows/workflow-release_task-publishGithub.yml@main
    with:
      comments: ${{ github.event.inputs.comments }}
    secrets:
      BP_PAT: ${{ secrets.BP_PAT_TOKEN }}
